[package]
name = "hallings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# For debugging and logging
yew = { version = "0.20", features = ["csr"] }
stylist = {version = "0.11", features = ["yew_integration"] }
web-sys = "0.3.60"
wasm-bindgen = "0.2.83"
